sudo: required

services:
  - docker

env:
  global:
    - VERSION=deploy-20190110
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=inboxen
    - DOCKER_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=inboxen
    - QUAY_LOGIN=crazymax
    - secure: Rd3MfyeNZMUxqZj+7wCCMrxs5hiJm66+IBL8x27iw3Yq1McI++2JJD0IZwdniNYN+SNVzSdHwCDaJ5bG2iZpR6jeWg25+v0b5JIlPkZLvXMKzvBdY/SCNCu7lk88J1x2GHDtHPSS0dJ2hcVJI14DQ/qTf9yGqcM2Xz02VCKcgoUgpx/SP+PoNHiClZTxQflT6LBHK3wOXGcbowYQ134E5sVFaHsXGMnlTOwImMd/O50Mw+gkvGkBnkNW0eaCzWHw3efHysqk9VhPyvKSkDi8MAn94gibpIXSJvG9cWecVwtzWVPOKnsFnJEE4wA6UjFF9Ky+HFLH9yHNOu7sOcw3Hl1ed/iFQPGm931vXXjlUMb2HiDqFcLoK4f+BY/URSR9nIBQ0M3iPGvUqupAoJdFP579jghVwV98gf9nXYtChOfmHNA/pSl7PUDzCWAbQBocHJ85/SZ7EH/7MUAfQq84v5aDADFzAe23Pn6VCKNEpt/5qOdx0l0rk65Kx17SXqQwh5ExYNZpnzz6Y1mTd/NHweoGFrnLU27eIB5P8jA9XTO+KyBbF4fJ7Ytduxx+7LSwwry1k6a5HAEs4iLMq2t7izwk1pw9U+dMQPKpG5H4pK7KjVYxJELSGeLCkegRXAScyGixiGrcYQvfUN7XKcIoOB6MMGGlrE9AUKOvzE4tEpg= # DOCKER_PASSWORD
    - secure: hSwprjkM9cUFo7ukv/yKULe52fstEL2Ccvp6ATYkaPpAAPa4BFt5W8OrCF/Wi0YlY/12rjTM90vWfv0Gat9MnviI72C2Y27U05Qh2qW7rTJsxY6m5fVOWFJu0RnxQH8NI2+K9x12QGx5o4WhwrFGQtiZDkRQ/x/NOSGjOitFgV4OhT9IFq5x7Lvz/mcVKde9WfZcsd4M4DvVe51qgIb8F6o+GxFhReOeyu/lHiZo4fKtgFJDbm8vJ5JHhf+NIEU1wu4aeyGX1KQWYyj/jjyJGmPgfCTRaIpRAVcH9Zr9rwNB3oWV3zM+ejLYPBaVFzurmUNMaLGyA4l5f6kymbQ2e2qrm+i5puVvgrBOehfZrSSH8FDQ8wjGf8ZuVnbYwvxCW+x/aeZXwVJNMAFMGl3zJ5Cu0v76ELEUxSIZEzuQjSgNvMwE4pfR+DMLpu1vP6U09a/058ZSQxNlaShYm7bqQtAQzgyCWiIG4/c7Iu1L4fGeUz0JmzujwPrPayBiwImFmLwVYMZ4/H3yNI2Q1WrmSm5z6aQQBVjAxUo2uow8cGS5bMSa4iIfkYULJnbszgiJ/Xl+R5XW2bUXFR7s0sglREnfJ/Kdc5m6XMHlfL0AxV//MecYTGCPEgMpZ29EAjd8SjHfRpSe+0dF9c8jjg4fKeBS66ZOeE3s/EQb5P2LkQw= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
