version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=example.com"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@example.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: postgres:9.6
    container_name: inboxen_db
    hostname: db
    environment:
      - "TZ=${TZ}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    restart: always

  rabbitmq:
    image: rabbitmq:3.7
    container_name: inboxen_rabbitmq
    hostname: rabbitmq
    restart: always

  inboxen:
    image: crazymax/inboxen:latest
    container_name: inboxen
    depends_on:
      - db
      - rabbitmq
    ports:
      - target: 8823
        published: 8823
        protocol: tcp
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=inboxen"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:inboxen.example.com"
    env_file:
      - "./inboxen.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_TIMEOUT=30"
      - "IB_DB_HOST=db"
      - "IB_DB_PORT=5432"
      - "IB_DB_NAME=${POSTGRES_DB}"
      - "IB_DB_USER=${POSTGRES_USER}"
      - "IB_DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "IB_TASKS_BROKER_URL=amqp://guest:guest@rabbitmq:5672//"
    restart: always
